spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/popcon
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    generate-ddl: true
  profiles:
    include: API-KEY
  cloud:
    gcp:
      credentials:
        location: classpath:coral-sum-368108-cd6003507664.json
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

# S3
cloud:
  aws:
    credentials:
        accessKey: AKIAQIDXSJQ7NXNKPWHP
        secretKey: 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
    s3:
      bucket: popconbucket
    region:
      static: ap-northeast-2
    stack:
      auto: false


logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

gcp:
  config:
    file: coral-sum-368108-cd6003507664.json
  project:
    id: coral-sum-368108
  bucket:
    id: popcon
  dir:
    name: images
