spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/popcon
    username: root
    password: ssafy
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
    generate-ddl: true
  profiles:
    include: API-KEY
server :
  error :
    include-exception: false      # Response 에 Exception 을 표시할지
    include-message: always      # Response 에 Exception Message 를 표시할지 (never | always | on_param)
    include-stacktrace: never
